# Generated by Django 6.0.6 on 2026-06-28 14:01

import django.core.validators
import django.db.models.deletion
import employee.services.image
import employee.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('abbreviation', models.CharField(blank=True, max_length=50, verbose_name='略称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('enterprise_id', models.CharField(max_length=50, unique=True, verbose_name='EID')),
                ('staff_code', models.CharField(max_length=8, unique=True, verbose_name='社員番号')),
                ('work_start_date', models.DateField(verbose_name='入社日')),
                ('work_end_date', models.DateField(blank=True, null=True, verbose_name='退職日')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=employee.services.image.generate_profile_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'heic'], message='JEPG、PNG、WEBP、HEIC形式の画像のみアップロードできます。'), employee.validators.validate_image, employee.validators.validate_image_size], verbose_name='プロフィール画像')),
                ('first_name', models.CharField(max_length=50, verbose_name='名')),
                ('last_name', models.CharField(max_length=50, verbose_name='姓')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='ミドルネーム')),
                ('first_name_furigana', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='全角カタカナで入力してください。', regex='^[ァ-ヶー]+$')], verbose_name='名(フリガナ)')),
                ('last_name_furigana', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='全角カタカナで入力してください。', regex='^[ァ-ヶー]+$')], verbose_name='姓(フリガナ)')),
                ('middle_name_furigana', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='全角カタカナで入力してください。', regex='^[ァ-ヶー]+$')], verbose_name='ミドルネーム(フリガナ)')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('postal_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='郵便番号はハイフンなしの7桁で入力してください。', regex='^\\d{7}$')], verbose_name='郵便番号')),
                ('prefecture', models.CharField(choices=[('01', '北海道'), ('02', '青森県'), ('03', '岩手県'), ('04', '宮城県'), ('05', '秋田県'), ('06', '山形県'), ('07', '福島県'), ('08', '茨城県'), ('09', '栃木県'), ('10', '群馬県'), ('11', '埼玉県'), ('12', '千葉県'), ('13', '東京都'), ('14', '神奈川県'), ('15', '新潟県'), ('16', '富山県'), ('17', '石川県'), ('18', '福井県'), ('19', '山梨県'), ('20', '長野県'), ('21', '岐阜県'), ('22', '静岡県'), ('23', '愛知県'), ('24', '三重県'), ('25', '滋賀県'), ('26', '京都府'), ('27', '大阪府'), ('28', '兵庫県'), ('29', '奈良県'), ('30', '和歌山県'), ('31', '鳥取県'), ('32', '島根県'), ('33', '岡山県'), ('34', '広島県'), ('35', '山口県'), ('36', '徳島県'), ('37', '香川県'), ('38', '愛媛県'), ('39', '高知県'), ('40', '福岡県'), ('41', '佐賀県'), ('42', '長崎県'), ('43', '熊本県'), ('44', '大分県'), ('45', '宮崎県'), ('46', '鹿児島県'), ('47', '沖縄県')], default='13', max_length=2, verbose_name='都道府県')),
                ('city', models.CharField(max_length=50, verbose_name='市区町村')),
                ('address1', models.CharField(max_length=50, verbose_name='町名・丁目・番地')),
                ('address2', models.CharField(blank=True, max_length=50, verbose_name='建物名・部屋番号')),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='ハイフンなしの10～11桁で入力してください。', regex='^\\d{10,11}$')], verbose_name='電話番号')),
                ('mobile_phone_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='ハイフンなしの10～11桁で入力してください。', regex='^\\d{10,11}$')], verbose_name='携帯電話番号')),
                ('personal_email', models.EmailField(max_length=254, verbose_name='個人用メールアドレス')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('abbreviation', models.CharField(blank=True, max_length=50, verbose_name='略称')),
                ('description', models.TextField(verbose_name='説明')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='トレーニング名')),
                ('mandatory', models.BooleanField(default=False, verbose_name='必須')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限日')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('abbreviation', models.CharField(blank=True, max_length=50, verbose_name='略称')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='employee.account', verbose_name='アカウント名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='部署名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='employee.department', verbose_name='親部署名')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_departments', to='employee.employee', verbose_name='リード')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('start_date', models.DateField(verbose_name='所属開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='所属終了日')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='employee.department', verbose_name='部署名')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_histories', to='employee.employee', verbose_name='社員')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='account',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='employee.industry', verbose_name='インダストリー'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(verbose_name='説明')),
                ('started_at', models.DateField(verbose_name='開始日')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='employee.client', verbose_name='クライアント名')),
                ('lead_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leading_projects', to='employee.employee', verbose_name='リードマネージャー')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('role', models.CharField(max_length=50, verbose_name='役割')),
                ('allocation_rate', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(5)], verbose_name='稼働率')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_histories', to='employee.employee', verbose_name='社員')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employee.project', verbose_name='プロジェクト名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('join_date', models.DateField(verbose_name='入社日')),
                ('recruitment_type', models.CharField(choices=[('BRAND_NEW', '新卒'), ('SECOND_NEW', '第二新卒'), ('EXPERIENCED', '中途')], max_length=11, verbose_name='採用区分')),
                ('recruitment_route', models.CharField(choices=[('INTERNSHIP', 'インターンシップ'), ('HOMEPAGE', 'ホームページ'), ('JOB_WEBSITE', '求人サイト'), ('AGENT', 'エージェント'), ('REFERRAL', 'リファラル'), ('ALUMNI', 'アルムナイ(カムバック)'), ('HEAD_HUNTING', 'ヘッドハンティング'), ('SCOUNT', 'スカウト'), ('SNS', 'SNS'), ('EVENT', '採用イベント')], max_length=12, verbose_name='応募経路')),
                ('memo', models.TextField(blank=True, verbose_name='備考')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment', to='employee.employee', verbose_name='社員')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruited_employees', to='employee.employee', verbose_name='リクルーター')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='employee.category', verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('level', models.PositiveIntegerField(choices=[(1, '未経験'), (2, '初心者(補助があればできる)'), (3, '中級(レビューを受けながら自走できる)'), (4, '上級(他人に教えられる)'), (5, 'エキスパート')], default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='レベル')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='employee.employee', verbose_name='社員')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_skills', to='employee.skill', verbose_name='スキル')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('status', models.CharField(choices=[('NOT_STARTED', '未受講'), ('IN_PROGRESS', '受講中'), ('COMPLETED', '完了'), ('CANCELLED', 'キャンセル')], default='NOT_STARTED', max_length=20, verbose_name='ステータス')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='受講開始日')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='受講完了日')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='employee.employee', verbose_name='社員')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.training', verbose_name='トレーニング')),
            ],
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name', 'client'), name='uq_name_by_client'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='uq_name_by_category'),
        ),
        migrations.AddConstraint(
            model_name='employeeskill',
            constraint=models.UniqueConstraint(fields=('employee', 'skill'), name='uq_skill_by_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeetraining',
            constraint=models.UniqueConstraint(fields=('employee', 'training'), name='uq_training_by_employee'),
        ),
    ]
